name: E2E Tests (Manual)

# E2E tests are slow (5+ min) and can be flaky in CI
# Run manually or on-demand only - not required for PR merge
# For PR validation, use the fast build-validation.yml workflow instead

on:
  # Manual trigger only - add label "run-e2e" to PR to trigger
  pull_request:
    types: [labeled]
    branches: [main, develop]
  workflow_dispatch:
  # Optional: Run nightly
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # Only run if: manually triggered, scheduled, or PR has "run-e2e" label
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run-e2e'))

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    env:
      # Supabase environment variables for waitlist tests
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || 'https://placeholder.supabase.co' }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || 'placeholder-key' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install root dependencies
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run E2E tests
        working-directory: ./frontend
        run: npx playwright test --project=${{ matrix.browser }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: frontend/test-results/
          retention-days: 30

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.browser }}
          path: frontend/test-screenshots/
          retention-days: 30

      - name: Upload videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: videos-${{ matrix.browser }}
          path: frontend/test-results/artifacts/**/*.webm
          retention-days: 30

  report:
    name: Publish Test Report
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish HTML report
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report
          path: artifacts/**/html/
          retention-days: 30
